# Generated by Django 4.2.1 on 2023-05-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_network', models.CharField(max_length=50)),
                ('discount_card', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
