# Generated by Django 4.2.1 on 2023-05-21 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_stores_street_house_stores_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkSocNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True)),
                ('inst', models.URLField(blank=True)),
                ('vk', models.URLField(blank=True)),
                ('tik_tok', models.URLField(blank=True)),
                ('classmates', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('telegram', models.URLField(blank=True)),
                ('name_network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.storenetwork')),
            ],
        ),
    ]
