# Generated by Django 4.2.1 on 2023-05-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_stores_number_stars_stores_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stores',
            name='time_job',
        ),
    ]
