# Generated by Django 4.2.1 on 2023-05-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_promotionsregister_rename_worktime_openhours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='number_phone',
            field=models.IntegerField(blank=True),
        ),
    ]
