# Generated by Django 4.2.1 on 2023-05-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_stores_number_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openhours',
            name='friday',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='monday',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='saturday',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='sunday',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='thursday',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='tuesday',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='wednesday',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stores',
            name='number_phone',
            field=models.IntegerField(),
        ),
    ]
