# Generated by Django 4.2.1 on 2023-05-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_openhours_friday_alter_openhours_monday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
