# Generated by Django 4.2.1 on 2023-06-02 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_stores_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openhours',
            name='store',
        ),
        migrations.AddField(
            model_name='stores',
            name='open_hours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.openhours'),
        ),
    ]
