# Generated by Django 4.2.1 on 2023-06-15 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_stores_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openhours',
            name='store',
        ),
        migrations.RemoveField(
            model_name='promotiondays',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='promotiondays',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='promotiondays',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='promotiondays',
            name='store',
        ),
        migrations.RemoveField(
            model_name='promotiondays',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='promotiondays',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='promotiondays',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='promotiondays',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='promotiondays',
            name='promotion_days',
            field=models.ManyToManyField(to='main.promotionsregister'),
        ),
        migrations.AddField(
            model_name='stores',
            name='open_hours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.openhours'),
        ),
        migrations.AddField(
            model_name='stores',
            name='promotion_days',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.promotiondays'),
        ),
    ]
