# Generated by Django 4.2.1 on 2023-07-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_openhours_friday_remove_openhours_monday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openhours',
            name='fri_fn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='fri_st',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='mon_fn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='mon_st',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='sat_fn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='sat_st',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='sun_fn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='sun_st',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='thu_fn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='thu_st',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='tue_fn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='tue_st',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='wed_fn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='wed_st',
            field=models.DateTimeField(),
        ),
    ]
