# Generated by Django 4.2.1 on 2023-07-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_openhours_fri_fn_alter_openhours_fri_st_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='area',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='stores',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='stores',
            name='house',
        ),
        migrations.RemoveField(
            model_name='stores',
            name='street',
        ),
    ]
