# Generated by Django 4.2.1 on 2023-07-30 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_promotiondays_promotion_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='open_hours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.openhours'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='promotion_days',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.promotiondays'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='store_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.storenetwork'),
        ),
    ]
