# Generated by Django 4.2.1 on 2023-09-05 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_generalpromotions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionsregister',
            name='value',
        ),
        migrations.AddField(
            model_name='promotionsregister',
            name='general_promotions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.generalpromotions'),
        ),
        migrations.AddField(
            model_name='promotionsregister',
            name='store_network',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='promotionsregister',
            name='unique_value',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
