# Generated by Django 4.2.1 on 2023-09-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_promotionsregister_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionsregister',
            name='unique_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
