# Generated by Django 4.2.1 on 2023-09-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_promotionsregister_unique_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotionsregister',
            old_name='unique_value',
            new_name='value',
        ),
        migrations.AddField(
            model_name='promotionsregister',
            name='decoding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotionsregister',
            name='general_promotions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='GeneralPromotions',
        ),
    ]
