# Generated by Django 4.2.1 on 2023-09-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_unique_value_promotionsregister_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionsregister',
            name='store_network',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
