# Generated by Django 4.2.1 on 2023-09-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_promotionsregister_store_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openhours',
            name='fri_fn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='fri_st',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='mon_fn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='mon_st',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='sat_fn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='sat_st',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='sun_fn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='sun_st',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='thu_fn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='thu_st',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='tue_fn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='tue_st',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='wed_fn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='wed_st',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
