# Generated by Django 4.2.1 on 2023-09-11 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_openhours_fri_fn_alter_openhours_fri_st_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='shop_gallery')),
            ],
        ),
        migrations.AddField(
            model_name='stores',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.gallery'),
        ),
    ]
