# Generated by Django 4.2.1 on 2023-09-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_gallery_stores_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='size',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
