# Generated by Django 4.2.1 on 2023-10-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_stores_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stores',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
