# Generated by Django 4.2.1 on 2023-10-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_stores_number_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='storenetwork',
            name='classmates',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storenetwork',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storenetwork',
            name='inst',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storenetwork',
            name='link_home_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storenetwork',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storenetwork',
            name='tik_tok',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storenetwork',
            name='vk',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stores',
            name='link_shop',
            field=models.URLField(blank=True, null=True),
        ),
    ]
