# Generated by Django 4.2.1 on 2023-10-11 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_storenetwork_classmates_storenetwork_facebook_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linksocnetworks',
            old_name='link',
            new_name='link_home_page',
        ),
        migrations.RemoveField(
            model_name='linksocnetworks',
            name='name_network',
        ),
        migrations.RemoveField(
            model_name='storenetwork',
            name='classmates',
        ),
        migrations.RemoveField(
            model_name='storenetwork',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='storenetwork',
            name='inst',
        ),
        migrations.RemoveField(
            model_name='storenetwork',
            name='link_home_page',
        ),
        migrations.RemoveField(
            model_name='storenetwork',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='storenetwork',
            name='tik_tok',
        ),
        migrations.RemoveField(
            model_name='storenetwork',
            name='vk',
        ),
        migrations.AddField(
            model_name='storenetwork',
            name='links',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.linksocnetworks'),
        ),
    ]
