# Generated by Django 4.2.1 on 2023-10-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_rename_link_linksocnetworks_link_home_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storenetwork',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='store_network_logo'),
        ),
    ]
