# Generated by Django 4.2.1 on 2023-10-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_storenetwork_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionsregister',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='sale_gallery'),
        ),
    ]
