# Generated by Django 4.2.1 on 2023-10-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_promotionsregister_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionsregister',
            name='discount_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
