# Generated by Django 4.2.1 on 2023-10-17 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_promotionsregister_discount_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionsregister',
            name='image',
        ),
        migrations.AddField(
            model_name='promotionsregister',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.gallery'),
        ),
    ]
