# Generated by Django 4.2.1 on 2023-10-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_promotionsregister_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storenetwork',
            name='links',
        ),
        migrations.AddField(
            model_name='storenetwork',
            name='classmates',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storenetwork',
            name='inst',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storenetwork',
            name='link_home_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storenetwork',
            name='tik_tok',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storenetwork',
            name='vk',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LinkSocNetworks',
        ),
    ]
