# Generated by Django 4.2.1 on 2023-10-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_storenetwork_links_storenetwork_classmates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storenetwork',
            name='img_classmates',
            field=models.FileField(blank=True, null=True, upload_to='shop_gallery'),
        ),
        migrations.AddField(
            model_name='storenetwork',
            name='img_inst',
            field=models.FileField(blank=True, null=True, upload_to='shop_gallery'),
        ),
        migrations.AddField(
            model_name='storenetwork',
            name='img_tik_tok',
            field=models.FileField(blank=True, null=True, upload_to='shop_gallery'),
        ),
        migrations.AddField(
            model_name='storenetwork',
            name='img_vk',
            field=models.FileField(blank=True, null=True, upload_to='shop_gallery'),
        ),
    ]
