# Generated by Django 4.2.1 on 2023-10-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_storenetwork_img_classmates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storenetwork',
            name='image',
            field=models.ManyToManyField(to='main.gallery'),
        ),
    ]
