# Generated by Django 4.2.1 on 2023-10-25 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_storenetwork_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storenetwork',
            name='image',
        ),
        migrations.AddField(
            model_name='storenetwork',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.gallery'),
        ),
    ]
